apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hapi-fhir.fullname" . }}-db-secret
  labels:
    {{- include "hapi-fhir.labels" . | nindent 4 }}
type: Opaque
data:
  database-username: {{ .Values.database.username | b64enc | quote }}
  database-password: {{ .Values.database.password | b64enc | quote }}
