apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  database-name: {{ .Values.database.name | b64enc | quote }}
  database-username: {{ .Values.database.username | b64enc | quote }}
  database-password: {{ .Values.database.password | b64enc | quote }}
