apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  admin-username: {{ .Values.admin.username | b64enc | quote }}
  admin-password: {{ .Values.admin.password | b64enc | quote }}
  database-username: {{ .Values.database.username | b64enc | quote }}
  database-password: {{ .Values.database.password | b64enc | quote }}
