apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fhirhub-api.fullname" . }}
  labels:
    {{- include "fhirhub-api.labels" . | nindent 4 }}
type: Opaque
data:
  HAPI_FHIR_BASE_URL: {{ .Values.secrets.hapiFhirBaseUrl | b64enc | quote }}
  KEYCLOAK_AUTHORITY: {{ .Values.secrets.keycloakAuthority | b64enc | quote }}
  KEYCLOAK_AUDIENCE: {{ .Values.secrets.keycloakAudience | b64enc | quote }}
  KEYCLOAK_ADMIN_API_BASE_URL: {{ .Values.secrets.keycloakAdminApiBaseUrl | b64enc | quote }}
  KEYCLOAK_REALM: {{ .Values.secrets.keycloakRealm | b64enc | quote }}
  KEYCLOAK_BACKEND_CLIENT_ID: {{ .Values.secrets.keycloakBackendClientId | b64enc | quote }}
  KEYCLOAK_BACKEND_CLIENT_SECRET: {{ .Values.secrets.keycloakBackendClientSecret | b64enc | quote }}
