apiVersion: v2
name: fhirhub-api
description: FhirHub API Server
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: fhirhub-lib
    version: "0.1.0"
    repository: "file://../../fhirhub-lib"
